#!/usr/bin/env bash
# Build the Linux release bundle and wrap it in a .deb for beta testers.
#
# Runs inside WSL Ubuntu (or any x86_64 Debian/Ubuntu with the toolchain from
# wsl_setup.sh). The source tree is copied out of /mnt/... into the Linux
# filesystem first: building on DrvFs is slow enough to look hung.
#
#   wsl -d Ubuntu -- bash /mnt/d/.../tool/package/build_linux_deb.sh
#
# Output: dist/forelasning_<version>_amd64.deb next to the repo on the Windows side.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# Repo root as seen from this side of /mnt; overridable for a checkout elsewhere.
SRC_WIN="${1:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
WORK="$HOME/build/lecture_local"
FLUTTER_DIR="$HOME/sdk/flutter"
export PATH="$FLUTTER_DIR/bin:$PATH"

# x86_64 only. sherpa_onnx ships aarch64 too, but this script builds an amd64
# package; an arm64 desktop needs its own build and its own Architecture field.
if [ "$(uname -m)" != "x86_64" ]; then
  echo "This script builds the amd64 package; got $(uname -m)" >&2
  exit 1
fi

echo "==> Syncing source into the Linux filesystem"
mkdir -p "$WORK"
rsync -a --delete \
  --exclude '.git/' --exclude 'build/' --exclude '.dart_tool/' \
  --exclude 'dist/' --exclude '.idea/' --exclude 'android/key.properties' \
  "$SRC_WIN/" "$WORK/"

cd "$WORK"

VERSION="$(grep -m1 '^version:' pubspec.yaml | sed 's/^version:[[:space:]]*//' | tr -d '[:space:]')"
DEB_VERSION="${VERSION%%+*}"           # 1.0.0 from 1.0.0+1
BUILD_NUMBER="${VERSION##*+}"
echo "==> Version $DEB_VERSION (build $BUILD_NUMBER)"

echo "==> flutter pub get"
flutter pub get

echo "==> flutter build linux --release"
flutter build linux --release

BUNDLE="$WORK/build/linux/x64/release/bundle"
[ -x "$BUNDLE/lecture_local" ] || { echo "bundle missing at $BUNDLE" >&2; exit 1; }

echo "==> Staging .deb tree"
PKG="forelasning"
STAGE="$WORK/build/deb/$PKG"
rm -rf "$STAGE"
mkdir -p "$STAGE/DEBIAN" \
         "$STAGE/opt/$PKG" \
         "$STAGE/usr/bin" \
         "$STAGE/usr/share/applications" \
         "$STAGE/usr/share/pixmaps"

cp -r "$BUNDLE/." "$STAGE/opt/$PKG/"

# Replace the llama.cpp libraries with the ones built by
# tool/package/build_llamacpp_linux.sh. The prebuilt that llm_llamacpp
# downloads is linked against CUDA, and libggml-cuda.so needs libcuda.so.1 -
# the NVIDIA driver library, which cannot be bundled and cannot be pulled from
# apt without dragging in driver packages. Shipping it means every tester
# without an NVIDIA card records, transcribes, and then cannot load libllama.so
# at all. The locally built set is CPU-only with no GPU dependency.
LLAMACPP_LIBS="${LLAMACPP_LIBS:-$HOME/build/llamacpp-linux-x64}"
if ! ls "$LLAMACPP_LIBS"/libllama.so* >/dev/null 2>&1; then
  # Never fall through to the upstream prebuilt: the package would install fine
  # and then produce no brief for anyone without an NVIDIA driver. A warning is
  # not enough - nobody reads one three months from now - so build it instead.
  echo "==> no llama.cpp at $LLAMACPP_LIBS, building it"
  bash "$SCRIPT_DIR/build_llamacpp_linux.sh" "$LLAMACPP_LIBS"
fi
ls "$LLAMACPP_LIBS"/libllama.so* >/dev/null 2>&1 || {
  echo "no libllama.so in $LLAMACPP_LIBS - refusing to build a package whose brief cannot load" >&2
  exit 1
}

echo "==> substituting llama.cpp from $LLAMACPP_LIBS"
rm -f "$STAGE/opt/$PKG/lib/"libllama.so* "$STAGE/opt/$PKG/lib/"libggml*.so*
for f in "$LLAMACPP_LIBS"/*.so*; do
  [ -f "$f" ] || continue
  soname="$(objdump -p "$f" 2>/dev/null | awk "/SONAME/{print \$2}")"
  # CMake names the real file libfoo.so.0.20.1; the app opens libfoo.so, so
  # install under the plain name and let the SONAME pass below add the link.
  if [ -n "$soname" ]; then
    plain="${soname%%.so.*}.so"
  else
    plain="$(basename "$f")"
  fi
  cp "$f" "$STAGE/opt/$PKG/lib/$plain"
done
ls "$STAGE/opt/$PKG/lib/" | grep -E "llama|ggml" | sed "s/^/    /"

# Every library here sits under a plain filename (libggml.so) while its SONAME -
# and the DT_NEEDED entry each sibling uses - is versioned (libggml.so.0). True
# of the libraries substituted above (CMake versions its SONAMEs) and of the ones
# Flutter bundles. Left alone, dlopen("libllama.so") fails with
#   libggml.so.0: cannot open shared object file
# and the teacher gets a transcript but never a brief. Two fixes: add the SONAME
# beside each library as a symlink, and start the app through a wrapper that puts
# the bundle directory on the loader path, since RUNPATH is not inherited by a
# dlopened library.
for so in "$STAGE/opt/$PKG/lib"/*.so; do
  [ -f "$so" ] || continue
  soname=$(objdump -p "$so" 2>/dev/null | awk "/SONAME/{print \$2}")
  [ -n "$soname" ] || continue
  [ "$soname" = "$(basename "$so")" ] && continue
  ln -sf "$(basename "$so")" "$STAGE/opt/$PKG/lib/$soname"
done

cat > "$STAGE/usr/bin/$PKG" <<'LAUNCHER'
#!/bin/sh
# Generated by tool/package/build_linux_deb.sh - see the note about SONAMEs there.
LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/opt/PKGNAME/lib"
export LD_LIBRARY_PATH
exec /opt/PKGNAME/lecture_local "$@"
LAUNCHER
sed -i "s/PKGNAME/$PKG/g" "$STAGE/usr/bin/$PKG"
chmod 0755 "$STAGE/usr/bin/$PKG"

# Icons come from the Android launcher set, so each density goes in the hicolor
# directory matching its real pixel size - dropping a 192px PNG into 512x512/
# only makes every desktop scale it up and blur it. mdpi/hdpi/xhdpi/xxxhdpi are
# 48/72/96/192, all sizes hicolor's index.theme declares. /usr/share/pixmaps is
# the fallback for desktops that do not read the hicolor theme at all.
ICON_ID="se.axelkarlsson.lecture_local"
RES="$WORK/android/app/src/main/res"
for entry in "mdpi:48" "hdpi:72" "xhdpi:96" "xxxhdpi:192"; do
  density="${entry%%:*}"
  size="${entry##*:}"
  src="$RES/mipmap-$density/ic_launcher.png"
  [ -f "$src" ] || continue
  mkdir -p "$STAGE/usr/share/icons/hicolor/${size}x${size}/apps"
  cp "$src" "$STAGE/usr/share/icons/hicolor/${size}x${size}/apps/$ICON_ID.png"
done
if [ -f "$RES/mipmap-xxxhdpi/ic_launcher.png" ]; then
  cp "$RES/mipmap-xxxhdpi/ic_launcher.png" "$STAGE/usr/share/pixmaps/$ICON_ID.png"
fi

cat > "$STAGE/usr/share/applications/se.axelkarlsson.lecture_local.desktop" <<'DESKTOP'
[Desktop Entry]
Type=Application
Name=Föreläsning
GenericName=Lecture recorder
Comment=Spela in en lektion, transkribera lokalt och få ett underlag att klistra in
Exec=forelasning
Icon=se.axelkarlsson.lecture_local
Terminal=false
Categories=AudioVideo;Audio;
Keywords=lecture;transcription;swedish;föreläsning;
StartupWMClass=lecture_local
DESKTOP

# Highest glibc symbol version anything in the bundle actually asks for, so the
# floor tracks whatever got shipped rather than a number someone typed once. It
# matters: the upstream llama.cpp prebuilt needed GLIBC_2.38 (Ubuntu 24.04+),
# while building it here against this distro brings it down to 2.34. Declaring it
# makes apt refuse an old system up front instead of the app breaking later, at
# the moment the teacher asks for a brief.
GLIBC_MIN="$(objdump -T "$STAGE/opt/$PKG/lecture_local" "$STAGE/opt/$PKG/lib/"*.so 2>/dev/null || true)"
GLIBC_MIN="$(printf "%s" "$GLIBC_MIN" | grep -o "GLIBC_[0-9.]*" | sed "s/GLIBC_//" | sort -uV | tail -1)"
GLIBC_MIN="${GLIBC_MIN:-2.35}"
echo "==> requires glibc >= $GLIBC_MIN"

INSTALLED_KB="$(du -sk "$STAGE" | cut -f1)"

cat > "$STAGE/DEBIAN/control" <<CONTROL
Package: $PKG
Version: $DEB_VERSION-$BUILD_NUMBER
Section: sound
Priority: optional
Architecture: amd64
Maintainer: Axel Karlsson <axel.karlsson@hogia.se>
Installed-Size: $INSTALLED_KB
Depends: libgtk-3-0 (>= 3.24), libglib2.0-0, libstdc++6, libc6 (>= $GLIBC_MIN), pulseaudio-utils, libgomp1
Description: Föreläsning - lokal inspelning och transkribering av lektioner
 Spelar in en lektion, transkriberar svenska på enheten med KB-Whisper och
 skriver ett underlag som läraren kan klistra in i skolplattformen.
 .
 Ljud och transkript stannar på datorn om inte läraren aktivt väljer en
 EU-leverantör i inställningarna.
 .
 Modellerna laddas ned vid första användningen (flera hundra MB, upp till
 ~4,7 GB för den stora sammanfattningsmodellen).
CONTROL

# pulseaudio-utils is a hard dependency on purpose: record_linux captures PCM by
# shelling out to parecord, and without it recording fails at the moment the
# teacher presses start. A PipeWire desktop satisfies parecord from this package
# too (pipewire-pulse only replaces the server).

cat > "$STAGE/DEBIAN/postinst" <<'POSTINST'
#!/bin/sh
set -e
if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database -q /usr/share/applications || true
fi
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
fi
POSTINST
chmod 0755 "$STAGE/DEBIAN/postinst"

cat > "$STAGE/DEBIAN/postrm" <<'POSTRM'
#!/bin/sh
set -e
if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database -q /usr/share/applications || true
fi
POSTRM
chmod 0755 "$STAGE/DEBIAN/postrm"

find "$STAGE/opt/$PKG" -type f -name '*.so*' -exec chmod 0644 {} +
chmod 0755 "$STAGE/opt/$PKG/lecture_local"

echo "==> dpkg-deb --build"
OUT_DIR="$SRC_WIN/dist"
mkdir -p "$OUT_DIR"
DEB="$OUT_DIR/${PKG}_${DEB_VERSION}-${BUILD_NUMBER}_amd64.deb"
fakeroot dpkg-deb --build --root-owner-group "$STAGE" "$DEB"

echo
echo "==> Built $DEB"
ls -lh "$DEB"
dpkg-deb --info "$DEB" | sed -n '1,20p'
